"""Add item_id to food_items

Revision ID: 065e436cc8f4
Revises: e8297494d54a
Create Date: 2026-03-10 15:35:09.538528
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '065e436cc8f4'
down_revision: Union[str, None] = 'e8297494d54a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_items', sa.Column('item_id', sa.String(length=255), nullable=False, comment="Item ID, e.g. 'Ra00001-DK'."))
    op.create_unique_constraint(None, 'food_items', ['item_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'food_items', type_='unique')
    op.drop_column('food_items', 'item_id')
    # ### end Alembic commands ###