"""initial schema with food item uuid

Revision ID: 13cace0cd11e
Revises: 
Create Date: 2026-03-12 12:52:45.957633
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '13cace0cd11e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('global_backbone_versions',
    sa.Column('version', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('weights_blob', sa.Text(), nullable=False, comment='gzip-compressed, base64-encoded JSON of backbone weight arrays.'),
    sa.Column('algorithm', sa.String(length=10), nullable=False, comment="Algorithm this backbone belongs to: 'ts' or 'dqn'."),
    sa.Column('client_count', sa.Integer(), nullable=False, comment='Number of clients whose uploads contributed to this round.'),
    sa.Column('total_interactions', sa.Integer(), nullable=False, comment='Sum of n_k across all contributing clients for this round.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('substitution_groups',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('food_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_code', sa.String(), nullable=False, comment="External code / synthetic ID from dataset, e.g. 'food_001'."),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_id', sa.SmallInteger(), nullable=False),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('price_eur', sa.Numeric(precision=8, scale=2), nullable=False, comment='Price of the item in EUR.'),
    sa.Column('serving_size_g', sa.Numeric(precision=8, scale=2), nullable=False, comment='Nominal serving size in grams.'),
    sa.Column('co2_kg_per_kg', sa.Numeric(precision=10, scale=4), nullable=False, comment='CO2 emission per kg of product (kg CO2e/kg).'),
    sa.Column('co2_kg_per_serving', sa.Numeric(precision=10, scale=4), nullable=False, comment='Pre-computed CO2 emission for a single serving (kg CO2e).'),
    sa.Column('calories_kcal', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('carbs_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fiber_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('sugar_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('processing_level', sa.Integer(), nullable=True),
    sa.Column('is_meat', sa.Boolean(), nullable=False),
    sa.Column('is_dairy', sa.Boolean(), nullable=False),
    sa.Column('is_plant_based', sa.Boolean(), nullable=False),
    sa.Column('is_vegan', sa.Boolean(), nullable=False),
    sa.Column('is_vegetarian', sa.Boolean(), nullable=False),
    sa.Column('is_gluten_free', sa.Boolean(), nullable=False),
    sa.Column('allergens', sa.JSON(), nullable=False, comment="Array of allergen codes, e.g. ['milk', 'soy']."),
    sa.Column('item_metadata', sa.JSON(), nullable=False, comment='Arbitrary item metadata from the source catalogue.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_code')
    )
    op.create_table('food_item_substitution_groups',
    sa.Column('food_item_id', sa.UUID(), nullable=False),
    sa.Column('substitution_group_id', sa.SmallInteger(), nullable=False),
    sa.Column('group_priority', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['substitution_group_id'], ['substitution_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('food_item_id', 'substitution_group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_item_substitution_groups')
    op.drop_table('food_items')
    op.drop_table('substitution_groups')
    op.drop_table('global_backbone_versions')
    op.drop_table('categories')
    # ### end Alembic commands ###