"""Adjust food_items schema

Revision ID: e8297494d54a
Revises: 001
Create Date: 2026-03-10 15:21:58.964640
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e8297494d54a'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_items', sa.Column('co2e_emission_tonnes', sa.Float(), nullable=False, comment='CO2e emission in tonnes.'))
    op.drop_column('food_items', 'co2e_score')
    op.drop_column('food_items', 'co2e_kg_per_kg')
    op.drop_column('food_items', 'unit')
    op.alter_column('global_backbone_versions', 'algorithm',
               existing_type=sa.VARCHAR(length=10),
               comment="Algorithm this backbone belongs to: 'ts' or 'dqn'.",
               existing_comment="'ts' or 'dqn'.",
               existing_nullable=False)
    op.alter_column('global_backbone_versions', 'client_count',
               existing_type=sa.INTEGER(),
               comment='Number of clients whose uploads contributed to this round.',
               existing_comment='Number of clients that contributed to this round.',
               existing_nullable=False)
    op.alter_column('global_backbone_versions', 'total_interactions',
               existing_type=sa.INTEGER(),
               comment='Sum of n_k across all contributing clients for this round.',
               existing_comment='Sum of n_k across contributing clients.',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('global_backbone_versions', 'total_interactions',
               existing_type=sa.INTEGER(),
               comment='Sum of n_k across contributing clients.',
               existing_comment='Sum of n_k across all contributing clients for this round.',
               existing_nullable=False)
    op.alter_column('global_backbone_versions', 'client_count',
               existing_type=sa.INTEGER(),
               comment='Number of clients that contributed to this round.',
               existing_comment='Number of clients whose uploads contributed to this round.',
               existing_nullable=False)
    op.alter_column('global_backbone_versions', 'algorithm',
               existing_type=sa.VARCHAR(length=10),
               comment="'ts' or 'dqn'.",
               existing_comment="Algorithm this backbone belongs to: 'ts' or 'dqn'.",
               existing_nullable=False)
    op.add_column('food_items', sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('food_items', sa.Column('co2e_kg_per_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Raw CO2e in kg per kg of product (Poore & Nemecek 2018).'))
    op.add_column('food_items', sa.Column('co2e_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Normalised sustainability score 0–1. Higher = more sustainable.'))
    op.drop_column('food_items', 'co2e_emission_tonnes')
    # ### end Alembic commands ###